### ISSUE TITLE
Feature Request: Allow selected svg to be saved as .svg file in storage system

### ISSUE THREAD

**Issue by vesper8** [AlexAzartsev/heroicon#8]
I would find it very useful in my use-case if there was an option to save the selected SVG as a file in a given path. Any chance you could add this feature?

Many thanks

**Comment by AlexAzartsev** [comment]
Hi, sorry for delay, but I will consider to add this possibility as soon as possible.
Thx for use of my package :)

**Comment by AlexAzartsev** [comment]
Can you describe more what you want to achieve, at what stage icons should become downloadable?
on detail and view screens ?

**Comment by vesper8** [comment]
In my app I need the .svg files to be linkable in the public folder, so my api returns a url to the svg file, rather than returning the inline svg.

I achieved this rather simply by adding a model observer and storing the inline svg resulting from your picker to a file and saving that path on a different field in the db:

```

<?php

namespace Observers;

use Models\Message;

class MessageObserver
{
    public function updating(Message $message)
    {
        if ($message->isDirty('asset_icon')) {
            $filename = sprintf('assets/messages/%s.svg', md5($message->asset_icon));
            \Storage::disk('local')->put(sprintf('public/%s', $filename), $message->asset_icon, 'public');
            $message->asset_path = $filename;
        }
    }
}

```

**Comment by AlexAzartsev** [comment]
Good solution, so it means everything works :)
As Alternative you can create a special route, that will serve selected icons from db and will return content of selected icon with special headers , so browser will initiate file download with specified name.

I will close issue then :)
